# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16843f708768f1085e4138f233754b99f006cbfe4c0aa29120886916b33bd1a9f1fbc9a01620b2f19c5b7903e2f23a25ae9550c052669c691ee801184fd02d48

test:
  secret_key_base: 66efb336510e39773609624b915c86c985751ae53b247c98def006078595a316798c5e5110291bb00605bbba04cab89e58b92e6628a9493bdd57066f266fe1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
